name: Update Waka in README

'on':
  schedule:
    - cron: 0 * * * *

jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@V3
        with:
          WAKATIME_API_KEY: '${{ secrets.WAKATIME_API_KEY }}'
          GH_TOKEN: '${{ secrets.GH_TOKEN }}'
          SHOW_TOTAL_CODE_TIME: true